"""LUMYD Teacher-Student Local SLM Fine-Tuning Guide & Dataset Inspector

Inspects the accumulated distillation dataset generated by Gemini (The Teacher)
and prepares it for training a local Small Language Model (SLM) such as
Qwen2.5-Coder-1.5B/3B, Llama-3.2-1B/3B, or Mistral.
"""

import io
import json
import os
from pathlib import Path
import sys

# Fix Windows console encoding
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")


def inspect_and_guide():
    dataset_path = Path("backend/data/teacher_distillation_dataset.jsonl")
    if not dataset_path.exists() and Path("data/teacher_distillation_dataset.jsonl").exists():
        dataset_path = Path("data/teacher_distillation_dataset.jsonl")

    print("=" * 75)
    print("LUMYD TEACHER-STUDENT DISTILLATION INSPECTOR & SLM FINE-TUNING GUIDE")
    print("=" * 75)

    if not dataset_path.exists():
        print(f"[!] No distillation dataset found at {dataset_path} yet.")
        print("    Ask queries in the LUMYD Analyst Panel to accumulate teacher data.")
        return

    records = []
    with open(dataset_path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                try:
                    records.append(json.loads(line.strip()))
                except Exception:
                    pass

    total = len(records)
    print(f"[+] Total Distillation Records Accumulated: {total}")
    file_size_kb = dataset_path.stat().st_size / 1024
    print(f"[+] Dataset File Size: {file_size_kb:.2f} KB ({dataset_path})")

    # Dialect breakdown
    dialects = {}
    intents = {}
    sources = {}
    for r in records:
        lang = r.get("language", "unknown")
        dialects[lang] = dialects.get(lang, 0) + 1
        intent = r.get("intent_label", "unknown")
        intents[intent] = intents.get(intent, 0) + 1
        src = r.get("source", "unknown")
        sources[src] = sources.get(src, 0) + 1

    print("\nLanguage / Dialect Breakdown:")
    for lang, count in dialects.items():
        print(f"  - {lang:12}: {count:3} ({count/total*100:.1f}%)")

    print("\nKnowledge Source Breakdown:")
    for src, count in sources.items():
        print(f"  - {src:15}: {count:3} ({count/total*100:.1f}%)")

    print("\nTop Analytical Intents Learned:")
    for intent, count in sorted(intents.items(), key=lambda x: x[1], reverse=True)[:5]:
        print(f"  - {intent:30}: {count:3}")

    print("\n" + "-" * 75)
    print("HOW TO FINE-TUNE YOUR LOCAL SMALL LANGUAGE MODEL (SLM)")
    print("-" * 75)
    print("""
Recommended Base Models:
  1. Qwen/Qwen2.5-Coder-1.5B-Instruct (High efficiency on CPU/GPU, specialized in Python)
  2. meta-llama/Llama-3.2-1B-Instruct (Ultra-fast, multilingual support)
  3. Qwen/Qwen2.5-Coder-3B-Instruct (State-of-the-art code generation under 4GB VRAM)

Training Setup with Unsloth / Hugging Face PEFT LoRA:

```python
from unsloth import FastLanguageModel
import torch
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments

# 1. Load Model (4-bit quantization fits in 6GB GPU or Google Colab free tier)
max_seq_length = 2048
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="Qwen/Qwen2.5-Coder-1.5B-Instruct",
    max_seq_length=max_seq_length,
    load_in_4bit=True,
)

# 2. Add LoRA Adapters
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
)

# 3. Load LUMYD Distillation Dataset
dataset = load_dataset("json", data_files="backend/data/teacher_distillation_dataset.jsonl")

# 4. Format Prompt (Alpaca / ChatML)
def formatting_prompts_func(examples):
    instructions = examples["instruction"]
    queries = examples["query"]
    codes = examples["python_code"]
    explanations = examples["human_explanation"]
    texts = []
    for inst, q, code, exp in zip(instructions, queries, codes, explanations):
        text = f"<|im_start|>system\\n{inst}<|im_end|>\\n<|im_start|>user\\n{q}<|im_end|>\\n<|im_start|>assistant\\n```python\\n{code}\\n```\\n\\n{exp}<|im_end|>"
        texts.append(text)
    return {"text": texts}

formatted_dataset = dataset.map(formatting_prompts_func, batched=True)

# 5. Train
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=formatted_dataset["train"],
    dataset_text_field="text",
    max_seq_length=max_seq_length,
    args=TrainingArguments(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=5,
        max_steps=60,
        learning_rate=2e-4,
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        logging_steps=1,
        output_dir="outputs",
    ),
)
trainer.train()

# 6. Save GGUF for Ollama or Local Llama.cpp Inference
model.save_pretrained_gguf("lumyd_local_slm", tokenizer, quantization_method="q4_k_m")
```

Once fine-tuned, the local GGUF model can replace Gemini entirely, running locally
on your machine with zero cloud dependencies and zero API costs!
""")
    print("=" * 75)


if __name__ == "__main__":
    inspect_and_guide()
